// Generated by https://quicktype.io


export interface IProductResponse {
    codigoRetorno:  string;
    mensajeRetorno: string;
    data:           Product[];
}


export interface Product {
    id:          number;
    description: string;
    price:       number;
    status:      string;
    detail:      string;
    image:       string;
    isActive:    boolean;
    createdAt:   null;
    updatedAt:   null;
}

